dependencies:
  shared:
    default:
      r2.1:
      r2.3:
      r2.4:
    dev:
      shared:
        - gem: beaker-task_helper
          version: ['>= 1.1.0', '< 2.0.0']
        - gem: gettext-setup
          version: '~> 0.26'
        - gem: metadata-json-lint
          version: ['>= 2.0.2', '< 3.0.0']
        - gem: mocha
          version: ['>= 1.0.0', '< 1.2.0']
        - gem: parallel_tests
          version: ['>= 2.14.1', '< 2.14.3']
        - gem: pry
          version: '~> 0.10.4'
        - gem: puppet-lint
          version: ['>= 2.3.0', '< 3.0.0']
        - gem: puppet_pot_generator
          version: '~> 1.0'
        - gem: puppet-syntax
          version: ['>= 2.4.1', '< 3.0.0']
        - gem: puppetlabs_spec_helper
          version: ['>= 2.3.1', '< 3.0.0']
        - gem: rainbow
          version: ['>= 2.0.0', '< 2.2.0']
        - gem: rspec-puppet
          version: ['>= 2.3.2', '< 3.0.0']
        - gem: rspec-puppet-facts
          version: '~> 1.8'
        - gem: rubocop
          version: '~> 0.49'
        - gem: rubocop-i18n
          version: '~> 1.0'
        - gem: rubocop-rspec
          version: '~> 1.15'
        - gem: rspec_junit_formatter
          version: '~> 0.2'
        - gem: specinfra
          version: '2.67.3'
      r2.1:
      r2.3:
      r2.4:
    system:
      shared:
        - gem: beaker-i18n_helper
          version: '~> 1.1'
        - gem: beaker-module_install_helper
          version: ['>= 0.1.4', '< 1.0.0']
        - gem: beaker-puppet_install_helper
          version: ['>= 0.7.1', '< 1.0.0']
        - gem: master_manipulator
          version: ['>= 2.1.1', '< 3.0.0']
      r2.1:
      r2.3:
      r2.4:
  posix:
    default:
      r2.1:
      r2.3:
      r2.4:
    dev:
      shared:
        - gem: simplecov
          version: ['>= 0.14.1', '< 1.0.0']
      r2.1:
      r2.3:
      r2.4:
    system:
      r2.1:
      r2.3:
      r2.4:
  win:
    default:
      shared:
        - gem: win32-dir
          version: '<= 0.4.9'
        - gem: win32-eventlog
          version: '<= 0.6.5'
        - gem: win32-process
          version: '<= 0.7.5'
        - gem: win32-security
          version: '<= 0.2.5'
        - gem: win32-service
          version: '<= 0.8.8'
      r2.1:
        - gem: nokogiri
          version: '1.7.2'
      r2.3:
      r2.4:
    dev:
      r2.1:
      r2.3:
      r2.4:
    system:
      r2.1:
      r2.3:
      r2.4:
